server:
  port: 7072

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java6user
      password: root
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: java6
    password: 123


jwt:
  secretkey: ${java6secretkey}
  audience: ${java6audience}
  issuer: ${java6issuer}

rabbitmq:
  exchange-user: user-exchange
  elasticregisterkey: elastic-register-key
  queueregisterelastic: elastic-register-queue
  queueRegister: register-queue